#!/usr/bin/env bash


alias 1='clear;echo;ls -1F $HOME/bin/1*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 2='clear;echo;ls -1F $HOME/bin/2*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 3='clear;echo;ls -1F $HOME/bin/3*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 4='clear;echo;ls -1F $HOME/bin/4*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 5='clear;echo;ls -1F $HOME/bin/5*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 6='clear;echo;ls -1F $HOME/bin/6*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 7='clear;echo;ls -1F $HOME/bin/7*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 8='clear;echo;ls -1F $HOME/bin/8*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias 9='clear;echo;ls -1F $HOME/bin/9*|cut -d / -f5|nl;echo;cd $HOME/bin'
alias x='clear;echo;ls -1F $HOME/bin/x*|cut -d / -f5|nl;echo;cd $HOME/bin'

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Shortcuts
alias drive="cd $HOME/Google Drive"
alias dl="cd $HOME/Downloads"
alias d="cd $HOME/Desktop"
alias dot="cd $HOME/dotfiles"

alias un='cd $HOME/Documents/Sandbox/unx/'
alias ve='/usr/bin/vim $HOME/Documents/Sandbox/unx/u/vim.txt'
alias fun='/usr/bin/vim $HOME/dotfiles/functions'
alias ytdl="/usr/local/bin/youtube-dl"
alias ytdlconfig='v .config/youtube-dl/config'
alias hyfn="rename 's/ /-/g' *"
alias nohyfn="rename 's/-/ /g' *"
alias underscore="rename 's/ /_/g' *"
alias nounderscore="rename 's/_/ /g' *"
alias m4v='rename s/.mp4/.m4v/ *.mp4'
alias mp4='rename s/.m4v/.mp4/ *.m4v'
alias log='vim $HOME/Library/Logs/Backups/111_home_syno_backup_log'
alias ne='/usr/bin/vim $HOME/Documents/Sandbox/unx/u/notes.txt'
alias pro='/usr/bin/vim $HOME/dotfiles/bash_profile'
alias rc='/usr/bin/vim $HOME/dotfiles/bashrc'
alias crypt='$HOME/bin/272-toggle-encrypt-decrypt.sh'
alias th='help test | less'

# Git
alias gs='git status'
alias ga='git add --all'
alias gc='git commit -m ""'
alias gb='git branch '

# John Stuff
alias f='open -a Finder '
alias openurl='~/bin/261-open-urls-from-list.sh'

alias h='history'
alias his='history | grep -i $@'
alias le='/usr/bin/vim $HOME/Documents/Sandbox/unx/u/languages.txt'
alias mac='echo "${greenf}main base station MAC address${reset}" && ifconfig en1 | grep ether | cut -c 7-'
alias out='ls -alh /private/var/log/*.out'
alias pic='cd $HOME/Pictures'
alias rd='$HOME/bin/550-find-and-delete-dupes-UNDER-DEVELOPMENT.sh'
alias send='$HOME/bin/240-send.sh'
# alias size='echo ${cyanf}Calculating size...${reset};du -sh 2>/dev/null'
alias sizeall='du -xh -d 1'
alias src='. $HOME/.aliases && . $HOME/.bashrc && . $HOME/.bash_profile && . $HOME/.functions && clear && echo "${cyanf}Sourced...${reset}"'
alias sshconf='/usr/bin/vim $HOME/.ssh/config'
# alias synoroot='ssh -p 22022 admin@jde.i234.me'
alias vol='cd /Volumes;ls -lFgGhpU'

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
# alias update='brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update; sudo gem cleanup'

# alias bug='brew -v update; brew upgrade --force-bottle --cleanup; brew cleanup; brew cask cleanup; brew prune; brew doctor; echo "==> My Stuff"; brew list'

# List all files colorized in long format, excluding . and ..
alias l="ls -1F ${colorflag}"

# List all files colorized in long format, including hidden, excluding . and ..
alias ll="ls -lhAaF ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Get week number
alias week='date +%V'

# vim
alias v='/usr/bin/vim'

# Quit buffer
alias q='logout'

# Clear screen
alias c='clear'

# monitor long running jobs
# alias m=anybar_monitor

# alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Merge PDF files
# Usage 1: `mergepdf -o pages.pdf page1.pdf page2.pdf`
# Usage 2: `mergepdf -o pages.pdf *.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"
# Reindex Spotlight
alias spotover="sudo mdutil -E /"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

alias ytdlar='cd /Volumes/B-movie/archive-MASTER/06-youtube-COLLECTION ; /usr/bin/open -b "com.apple.Preview" "$(ls -tr | tail -n 1)"'

alias wan='curl whatismyip.akamai.com;echo'
alias al='/usr/bin/vim $HOME/Dotfiles/aliases'
# alias alsort='mv ~/.aliases .aliasestmp && sort -k 2 < .aliasestmp > .aliases && rm .aliasestmp'

alias b='cd $HOME/bin/'
alias service='$HOME/bin/980-service.sh'





